const mongoose = require('mongoose');

const ArtifactSchema = new mongoose.Schema({
  id: mongoose.Schema.Types.Mixed,
  hall: String,
  name: String,
  nameAr: String,
  arabic: String,
  period: String,
  meaning: String,
  meaningAr: String,
  symbol: mongoose.Schema.Types.Mixed,
  region: String,
  regionAr: String,
  year: String,
  category: String,
  categoryAr: String,
  significance: String,
  material: String,
  materialAr: String,
  location: String,
  locationAr: String,
  dimensions: String,
  inscription: String,
  inscriptionAr: String,
  verse: String,
  surah: String,
  concept: String,
  cipherType: String,
  mechanism: String,
  key: String,
  complexity: String,
  system: String,
  root: String,
  forms: [String],
  author: String,
  pages: String,
  condition: String,
  algorithm: String,
  accuracy: String,
  useCase: String
}, { strict: false });

module.exports = mongoose.model('Artifact', ArtifactSchema);
